# Generated by Django 3.2 on 2023-10-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_title_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(to='reviews.Genre'),
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='GenresTitles',
        ),
    ]
